2024-08-22 04:11:21.606140-03:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "CARDAPIO" already exists; SQL statement:
-- schema.sql

CREATE TABLE Cardapio (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    descricao TEXT NOT NULL,
    preco DECIMAL(1 [42101-232]
